name: Deploy PyPI package

on:
  create:
    tags:
      - "*.*.*"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pypi"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v8
      - name: Add poetry plugin
        run: poetry self add 'poetry-dynamic-versioning[plugin]'
      - name: Install dependencies
        run: make install_dependencies
      - name: Build the package
        run: make build
      - name: Publish package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish -u "__token__" -p "$PYPI_TOKEN"
